Packages
1. `torch`
    1. Functions
    2. Errors




CSS:
    1. function -
    <p style="background-color:#EEE;padding:10px;font-family:verdana;border-left:5px solid red">
            <span style="font-weight:bold" id="name">
                torch.cat
            </span> 
            <span style="font-style:italic" id="args">
                (tensors, dim=0, out=None) → Tensor
            </span>
    </p>
    
    2. Text
    <p style="font-size:16px">
    
    </p>
    
    <span style="font-size:16px">
    
    </span>

In [1]:
import torch

### 1. torch

#### i. Functions

<p style="background-color:#EEE;padding:10px;font-family:verdana;border-left:5px solid red">
    <span style="font-weight:bold" id="name">
        torch.cat
    </span> 
    <span style="font-style:italic" id="args">
        (tensors, dim=0, out=None) → Tensor
    </span>
</p>

<p style="font-size:16px">
    Concatenates the given **sequence** of seq tensors in the given dimension. All tensors must either have the same shape (except in the concatenating dimension) or be empty
</p>

<p style="background-color:#EEE;padding:10px;font-family:verdana;border-left:5px solid red">
        <span style="font-weight:bold" id="name">
            torch.nonzero
        </span> 
        <span style="font-style:italic" id="args">
            (input, out=None) → LongTensor
        </span>
</p>



<p style="font-size:16px">
    Returns a tensor containing the indices of all non-zero elements of input. Each row in the result contains the indices of a non-zero element in input. The result is sorted lexicographically, with the last index changing the fastest (C-style)
</p>


* <p style="font-size:16px">
      If input has n dimensions, then the resulting indices tensor out is of size $(z \times n)$, where z is the total number of non-zero elements in the input tensor i.e, if the tensor is of shape
  </p>

In [17]:
tensor_1d = torch.tensor([1, 1, 1, 0, 1])
print(f"No. of dimensions: {len(tensor_1d.shape)}")

tensor_nonzero = torch.nonzero(tensor_1d)
print(tensor_nonzero)
print(tensor_nonzero.shape)

No. of dimensions: 1
tensor([[0],
        [1],
        [2],
        [4]])
torch.Size([4, 1])


#### ii. Errors

`torch.mean`

1) <span style="color:red">RuntimeError</span>: Can only calculate the mean of floating types. Got Byte instead.


In [13]:
db = torch.randn(10) > 0.5
print(db)

torch.mean(db)

tensor([0, 0, 0, 0, 0, 0, 1, 0, 0, 1], dtype=torch.uint8)


RuntimeError: Can only calculate the mean of floating types. Got Byte instead.

`db` is of type Byte as the operation was boolean

**Solution**: 
<span style="font-size:16px">
    Change elements to float
</span>

In [14]:
db = torch.randn(10) > 0.5
print(db)

torch.mean(db.float())

tensor([0, 1, 0, 0, 0, 0, 0, 0, 1, 0], dtype=torch.uint8)


tensor(0.2000)