Q15) Given a neural network having a1,a2 as inputs, c1,c2 as outputs ,h1, h2 nodes of hidden layer and b1,b2 as biases. Network is initialized with the values and weights given in the graph? Your task is to perform 1 step of backpropagation and give the updated values for the weight w5 and w6.

<!--<img src="../img/quiz-backprop.jpg"> -->
<img src="https://lh5.googleusercontent.com/TxfaejDZ4C1x5DCz8T_kPGDZaH-cWv5gonRIeDfNJEeqcZZEX-CKajkifliEwH0uTcB53g6xfQ=w740">

In [1]:
import torch

In [2]:
a1 = torch.tensor([[0.05]], requires_grad=True)
a2 = torch.tensor([[0.10]], requires_grad=True)

b1 = torch.tensor([[0.35]], requires_grad=True)
b2 = torch.tensor([[0.60]], requires_grad=True)

w1 = torch.tensor([[0.15]], requires_grad=True)
w2 = torch.tensor([[0.20]], requires_grad=True)
w3 = torch.tensor([[0.25]], requires_grad=True)
w4 = torch.tensor([[0.30]], requires_grad=True)

w5 = torch.tensor([[0.40]], requires_grad=True)
w6 = torch.tensor([[0.45]], requires_grad=True)
w7 = torch.tensor([[0.50]], requires_grad=True)
w8 = torch.tensor([[0.55]], requires_grad=True)

In [3]:
h1 = a1*w1 + a2*w2 + b1
h2 = a1*w3 + a2*w4 + b1

print(h1)
print(h2)

tensor([[0.3775]], grad_fn=<AddBackward0>)
tensor([[0.3925]], grad_fn=<AddBackward0>)


In [4]:
c1 = h1*w5 + h2*w6 + b2
c2 = h1*w7 + h2*w8 + b2

print(c1)
print(c2)

tensor([[0.9276]], grad_fn=<AddBackward0>)
tensor([[1.0046]], grad_fn=<AddBackward0>)


In [5]:
# w5 and w6 are connected to c1

print(f"The gradient isn't set, right? {bool(w5.grad)}")

# call backward() on c1 to populate gradients in all tensors in its calculation
c1.backward()

The gradient isn't set, right? False


In [6]:
print(f"Is the gradient set now? {bool(w5.grad)}")
print(F"The gradient of w5: {w5.grad.item():.4f}\tw6: {w6.grad.item():.4f}")

Is the gradient set now? True
The gradient of w5: 0.3775	w6: 0.3925


In [7]:
# let learning rate be 0.2
with torch.no_grad():
  lr = 0.2
  w5 = w5 - w5.grad * 0.2
  w6 = w6 - w6.grad * 0.2
print(f"Updated values after one step of backprop w5:{w5.item():.3f}\tw6:{w6.item():.3f}")

Updated values after one step of backprop w5:0.324	w6:0.371
